# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Using Both Subdirectory Functions
#' 
#' These function serve as intermediaries between R and the subdirectory
#' source. 
#' 
#' @param x Vector of Numeric Values with length \eqn{n}.
#' 
#' @return A vector of numeric values with length \eqn{n}.
#' 
#' @rdname exported_funcs
#' @export
#' @examples
#' my_vec = c(3.5, 8, -1.5, -2, 0, 42)
#' calc_modifications(my_vec)
calc_modifications <- function(x) {
    .Call('_SubdirSrc_calc_modifications', PACKAGE = 'SubdirSrc', x)
}

#' @rdname exported_funcs
#' @export
#' @details
#' The exported function name is different from the subdirectory function. 
#' C++ does not allow duplicate function names with the same parameters. To 
#' preserve the original function name necessitates the subdirectory function
#' being placed behind a namespace, e.g. `A::calc_A_routine()`. Otherwise,
#' the name of the function exported must be different, e.g. `calc_A_export()`.
#' 
#' @examples
#' my_vecA = c(881, 884, 1,2,-4)
#' calc_A_export(my_vec)
calc_A_export <- function(x) {
    .Call('_SubdirSrc_calc_A_export', PACKAGE = 'SubdirSrc', x)
}

#' @rdname exported_funcs
#' @export
#' @examples
#' my_vecB = c(512,32, -1, 1.3, 5.9)
#' calc_B_export(my_vecB)
calc_B_export <- function(x) {
    .Call('_SubdirSrc_calc_B_export', PACKAGE = 'SubdirSrc', x)
}

